[start]
command:/usr/local/etc/rc.d/os-netbird start
parameters:%s
type:script
message:starting netbird instance

[stop]
command:/usr/local/etc/rc.d/os-netbird stop
parameters:%s
type:script
message:stopping netbird instance

[restart]
command:/usr/local/opnsense/scripts/netbird/netbird_restart.php
parameters:%s
type:script
message:restarting netbird instance

[status]
command:/usr/local/etc/rc.d/os-netbird status
parameters:%s
errors:no
type:script_output
message:get netbird instance status

[up]
command:/usr/local/opnsense/scripts/netbird/netbird_up.php
parameters:%s
type:script
message:set netbird instance up

[down]
command:/usr/local/opnsense/scripts/netbird/netbird_down.php
parameters:%s
type:script
message:set netbird instance down

[status-json]
command:/usr/local/opnsense/scripts/netbird/netbird_status.php
parameters:%s
errors:no
type:script_output
message:get netbird instance status in json format

[up-setup-key]
command:/usr/local/opnsense/scripts/netbird/netbird_up.php
parameters: %s -m %s -k %s
type:script_output
message:set netbird instance up with setup key

[sync-config]
command:/usr/local/sbin/pluginctl -c netbird_sync_config
type:script_output
message:sync netbird configuration
